name: Vite CI/CD Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create production .env file
        run: echo "VITE_SIGNALR_URL=${{ secrets.VITE_SIGNALR_URL }}" > .env.production

      - name: Lint
        run: npm run lint:fix

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
